root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./.tmp/main"
  cmd = "tailwindcss -c ./internal/pkg/presentation/web/css/tailwind.config.js -i ./internal/pkg/presentation/web/css/input.css -o ./assets/css/loran.css && templ generate && go build -o ./.tmp/main ./cmd/hemsida/main.go"
  delay = 1000
  exclude_dir = ["assets/css", "tmp", "vendor", "testdata", ".vscode"]
  exclude_file = []
  exclude_regex = [".*_templ.go","_test.go","output.css"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./.tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "toml", "html", "css", "js"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
